### ISSUE TITLE
RFR GPS tracking checks

### ISSUE THREAD

**Issue by LeonardoViotti** [LeonardoViotti/code-review#1]
The idea is basically an overlook at the code in general since this is my first code in pyspark.

- [x] If both codes, [checks](https://github.com/LeonardoViotti/Code-review/blob/master/RFR-GPS-tracking/intake_checks.py) and  [cleaining](https://github.com/LeonardoViotti/Code-review/blob/master/RFR-GPS-tracking/clean_and_aggregate.py), run with both sets of data, for Octuber 2019 and March 2020.
- [x] Check comprehension, is it easy to understand what's  the code supposed to do by the comments alone?
- [x] Is the code is in line with pyspark standards or best practices?
- [x] Check if there are efficiency bottlenecks preventing the code to run faster. 
- [x] If there are any evident mistakes errors.

**Comment by sebxwolf** [comment]
Thanks a lot for this checklist - very helpful! I've managed to reproduce your results, well done 🥇! Quite nice code and nice project. I learned a few syntax tricks I hadn't seen before, thanks 👍 . I tried to come up with a few constructive comments below; hope at least some of it can be of help.

- [x] If both codes, [checks](https://github.com/LeonardoViotti/Code-review/blob/master/RFR-GPS-tracking/intake_checks.py) and  [cleaining](https://github.com/LeonardoViotti/Code-review/blob/master/RFR-GPS-tracking/clean_and_aggregate.py), run with both sets of data, for Octuber 2019 and March 2020.
*Answer: After a few minor fixes, both scripts ran. The main thing that both scripts were lacking was the initialisation of a spark session (which isn't required on Databricks, so this is no issue in your production environment), and the import of the `_master.py` references. `clean_and_aggregate.py` had some file reference problems. See details in my commit. One minor suggestion would be: If you are running this code from the command line, it's convenient to assign the variables indicating the filenames of the files we want to load as an argument in the cl command, i.e. `python intake_checks.py 'file_name'`. This way you don't have to modify your code every time you want to process a new file (if that is sth that you do more than a few times, anyways).*

- [x] Check comprehension, is it easy to understand what's  the code supposed to do by the comments alone?
*Answer: Yes - all super clear. The only slightly unclear part was `Settings` in `clean_and_aggregate.py` - which month should be set? The year needs to be set in the dates and year vars, maybe this can be combined to avoid mismatch issues?*

- [x] Is the code is in line with pyspark standards or best practices?
*Answer: I'm not an expert on spark best practices but to me the code looks very much up to standard. Two minor suggestions: 
(1) Usually it is recommended to avoid calling `toPandas()` before exporting, but if we are sure that the file will comfortably fit in memory then that's fine. 
(2) I would suggest to do the joins with devices and roads with the aggregates after they have been called into memory with `toPandas()` or after they have been saved to csv (and loaded from csv). This also allows fixing potential merge issues without having to re-run the aggregation, and should also give a (probably very) small performance boost.*

- [x] Check if there are efficiency bottlenecks preventing the code to run faster. 
*Answer: It's a bit trial and error, but sometimes it can be faster to read from csv and write to parquet, and then run the aggregation on the parquet files. That's because spark can read parquet much faster than csv, and therefore also perform aggregations (which usually require multiple reads) much faster. Whether the added time to write to parquet is less than the time saved from faster aggregation is an empirical question. You could for example write the parquet file in the `intake_checks.py` script and then use it in the other script. However, since the aggregation steps here are limited, it could well be that it's not worth it.*

- [x] If there are any evident mistakes errors.  
*Answer: The aggregation seems flawless to me. As already mentioned, there were a few import issues I had when setting up to run on a docker container (so maybe tiny reproducibility issues), but nothing that affects the results. I tried to follow the logic of all aggregations thoroughly and did not find any issues.*
